export default [
  {
    files: ["components/**/*.js", "popup.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        location: "readonly",
        navigator: "readonly",
        chrome: "readonly",
        globalThis: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        console: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        FormData: "readonly",
        Promise: "readonly",
        Date: "readonly",
        Math: "readonly",
        JSON: "readonly",
        RegExp: "readonly",
        Set: "readonly",
        Map: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Symbol: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        ReferenceError: "readonly",
        escapeHtml: "readonly",
        htmlToADF: "readonly",
        sourceUrlBlock: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        ResizeObserver: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        XMLHttpRequest: "readonly",
        DOMException: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        atob: "readonly",
        btoa: "readonly",
        GlideRecord: "readonly",
        CSS: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-console": "off",
      "no-constant-condition": "warn",
      "no-unreachable": "error",
      "no-func-assign": "error",
      "no-extra-semi": "error",
      "semi": ["error", "always"],
      "no-empty": ["warn", { "allowEmptyCatch": true }],
      "no-var": "error",
      "prefer-const": "warn",
    },
  },
];
